server:
  port: 8091
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: user-service
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:h2test
#    username: sa
#    password:
  h2:
    console:
      path: /h2-console
      enabled: true
logging:
  level:
    root: info
    org.hibernate: info